### ISSUE TITLE
Consider using vfsgen for accessing/embedding resources.

### ISSUE THREAD

**Issue by dmitshur** [kevinburke/go-html-boilerplate#5]
Hey Kevin,

I suspect there's a good chance this project could be simplified, while still doing everything it's doing now, and more (like applying HTTP gzip compression of embedded static resources efficiently), by using [`vfsgen`](https://github.com/shurcooL/vfsgen#readme). Instead of `go-bindata` as it currently does.

Have you already considered `vfsgen`? Are you interested in exploring this direction?

I've created a similar but simpler project for getting started with GopherJS at https://github.com/gopherjs/gopherpen, which might be worth looking at as an example.

Let me know what you think, either way. Thanks for consideration!

**Comment by kevinburke** [comment]
Thanks for the suggestion! I think I am going to stick with what I have currently, as I'm pretty happy with it.
