### ISSUE TITLE
What was arguments to realize https

### ISSUE THREAD

**Issue by gintsgints** [kevinburke/go-html-boilerplate#7]
In my projects I prefer use nginx reverse proxy for https protocol.

What would be advantages of realizing https inside boilerplate?

**Comment by kevinburke** [comment]
If you have nginx running on the same machine, that's great; you probably don't need HTTPS here.

Advantages are:

- Your local setup is closer to your production setup so you can set Strict-Transport-Security headers without needing to branch based on environment.
- You can see mixed content warnings locally the same way they'd appear in the cluster.
- Go will serve HTTP/2 over HTTPS connections, but not HTTP connections.

**Comment by gintsgints** [comment]
Thank you
